# Generated by Django 4.2.11 on 2024-03-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arabic_word', models.CharField(max_length=255)),
                ('kyrgyz_word', models.CharField(max_length=255)),
                ('meaning', models.TextField()),
            ],
        ),
    ]
